// This file is generated by scripts/write-version.mjs. Do not edit manually.
export const appVersionInfo = {
  "version": "0.1.0",
  "git": {
    "describe": "v0.1.0-1-gd2afa41-dirty",
    "tag": "v0.1.0",
    "branch": "main",
    "commit": "d2afa41",
    "dirty": true,
    "commitDate": "2026-08-02T08:51:59+03:30"
  }
} as const;
