// This file is generated by scripts/write-version.mjs. Do not edit manually.
export const appVersionInfo = {
  "version": "0.1.0",
  "git": {
    "describe": "v0.1.0-2-g9c007ab-dirty",
    "tag": "v0.1.0",
    "branch": "main",
    "commit": "9c007ab",
    "dirty": true,
    "commitDate": "2026-08-08T13:48:37+03:30"
  }
} as const;
