// This file is generated by scripts/write-version.mjs. Do not edit manually.
export const appVersionInfo = {
  "version": "0.1.0",
  "git": {
    "describe": "v0.1.0-35-g02f1e83-dirty",
    "tag": "v0.1.0",
    "branch": "main",
    "commit": "02f1e83",
    "dirty": true,
    "commitDate": "2026-08-19T18:05:43+03:30"
  }
} as const;
