import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(rootDir, 'src', 'environments', 'version.ts');

const gitDir = path.join(rootDir, '.git');

function runGit(command, fallback = '') {
  try {
    return execSync(command, {
      cwd: rootDir,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
  } catch {
    return fallback;
  }
}

function readGitFile(relativePath) {
  try {
    return readFileSync(path.join(gitDir, relativePath), 'utf8').trim();
  } catch {
    return '';
  }
}

function readGitHeadFromFiles() {
  const head = readGitFile('HEAD');
  if (!head) {
    return { branch: 'unknown', commit: 'unknown' };
  }

  if (!head.startsWith('ref:')) {
    return { branch: 'detached', commit: head };
  }

  const refName = head.slice(5).trim();
  const commit = readGitFile(refName) || readPackedRef(refName) || 'unknown';
  const branch = refName.replace(/^refs\/heads\//, '') || 'unknown';
  return { branch, commit };
}

function readPackedRef(refName) {
  const packedRefs = readGitFile('packed-refs');
  if (!packedRefs) return '';

  for (const line of packedRefs.split(/\r?\n/)) {
    if (!line || line.startsWith('#') || line.startsWith('^')) continue;
    const [hash, ref] = line.split(' ');
    if (ref === refName) return hash;
  }
  return '';
}

function collectRefFiles(relativeDir, prefix = '') {
  const absoluteDir = path.join(gitDir, relativeDir);
  if (!existsSync(absoluteDir)) return [];

  return readdirSync(absoluteDir).flatMap((entryName) => {
    const absolutePath = path.join(absoluteDir, entryName);
    const refName = prefix ? `${prefix}/${entryName}` : entryName;
    if (statSync(absolutePath).isDirectory()) {
      return collectRefFiles(path.join(relativeDir, entryName), refName);
    }
    return [{ name: refName, hash: readFileSync(absolutePath, 'utf8').trim() }];
  });
}

function findTagForCommit(commitHash) {
  if (!commitHash || commitHash === 'unknown') return '';

  const looseTags = collectRefFiles('refs/tags');
  const packedTags = readGitFile('packed-refs')
    .split(/\r?\n/)
    .filter((line) => line && !line.startsWith('#') && !line.startsWith('^'))
    .map((line) => {
      const [hash, ref] = line.split(' ');
      return ref?.startsWith('refs/tags/') ? { name: ref.replace('refs/tags/', ''), hash } : null;
    })
    .filter(Boolean);

  const matchingTag = [...looseTags, ...packedTags].find((tagRef) => tagRef.hash === commitHash);
  return matchingTag?.name ?? '';
}

const packageJson = JSON.parse(readFileSync(path.join(rootDir, 'package.json'), 'utf8'));
const version = String(packageJson.version ?? '0.0.0');
const fileGit = readGitHeadFromFiles();
const commit = runGit('git rev-parse --short HEAD', fileGit.commit.slice(0, 7) || 'unknown');
const branch = runGit('git rev-parse --abbrev-ref HEAD', fileGit.branch);
const commitDate = runGit('git show -s --format=%cI HEAD', '');
const statusOutput = runGit('git status --short', '');
const dirty = statusOutput.length > 0;
const tag = runGit('git describe --tags --abbrev=0', findTagForCommit(fileGit.commit) || `v${version}`);
const describe = runGit('git describe --tags --dirty --always', `${tag || `v${version}`}${dirty ? '-dirty' : ''}`);

const versionInfo = {
  version,
  git: {
    describe,
    tag,
    branch,
    commit,
    dirty,
    commitDate
  }
};

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// This file is generated by scripts/write-version.mjs. Do not edit manually.\nexport const appVersionInfo = ${JSON.stringify(
    versionInfo,
    null,
    2
  )} as const;\n`,
  'utf8'
);
